### ISSUE TITLE
Discord Conversation about tic_tac_toe.cs

### ISSUE THREAD

**Issue by SHADOWELITE7** [SHADOWELITE7/Demo-Games#1]
Glaba writings from discord
``the tic tac toe game doesn't look that bad
I would recommend indenting consistently
and naming your variables consistently
indenting is VERY VERY important though
also, I'm pretty sure this code doesn't compile
it's got a lot of errors in it
from what I can see.``
``Issues are everywhere
it's all wrong
also, the code doesn't compile because there's a LOT of syntax errors
the overall logic seems reasonable though I guess.``

**Comment by daxtron2** [comment]
There is just so, so much wrong with this code. It basically needs to be rewritten entirely. Basically none of it is valid C# code.

**Comment by SHADOWELITE7** [comment]
ok
